services:
  - type: web
    name: github-contribution-graph
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: GITHUB_TOKEN
        sync: false
